"""Utility functions and constants for PubMed paper fetcher."""

# Academic institution keywords to exclude
ACADEMIC_KEYWORDS = {
    "university",
    "college",
    "school",
    "institute",
    "academia",
    "faculty",
    "department",
    "laboratory",
    "hospital",
    "clinic",
    "medical center",
    "health center",
    "research center",
    "national institutes",
    "center for",
    "foundation",
    "institution",
}

# Pharmaceutical/biotech company keywords to include
COMPANY_KEYWORDS = {
    # Company types
    "pharma",
    "therapeutics",
    "biotech",
    "biosciences",
    "biopharmaceuticals",
    "laboratories",
    "biopharma",
    "pharmaceuticals",
    "technologies",
    "diagnostics",
    "medicines",
    "biotechnology",
    "life sciences",
    
    # Legal entities
    "inc",
    "inc.",
    "llc",
    "ltd",
    "ltd.",
    "gmbh",
    "corp",
    "corp.",
    "co",
    "co.",
    "company",
    "ag",
    "sa",
    "nv",
    "plc",
    
    # Industry terms
    "drug",
    "health",
    "solutions",
    "systems",
    "products",
    "group",
    "holdings",
    "ventures",
    "discovery",
    "development",
    "research and development",
    "r&d",
    
    # Common company names (without typical endings)
    "pfizer",
    "novartis",
    "merck",
    "roche",
    "sanofi",
    "gsk",
    "astrazeneca",
    "bayer",
    "abbvie",
    "amgen",
    "gilead",
    "biogen",
    "moderna",
    "vertex",
    "regeneron",
    "alexion",
    "celgene",
    "genentech",
} 